### ISSUE TITLE
MultiWoz Dataset Processing

### ISSUE THREAD

**Issue by gumowangfei** [truthless11/MADPL#3]
Hello, regarding the data processing of this article, can you provide a more detailed description of the processing process?

**Comment by truthless11** [comment]
@gumowangfei Sure. In [Datamanager](https://github.com/truthless11/MADPL/blob/master/datamanager.py), our codes aim to get the `turn_data` at each dialog turn that includes the system dialog acts, user dialog acts, belief states, goal states, etc. The processed `turn_data` will be used for supervised policy pretraining. Note that here belief state (or called system state) and goal state (or called user state) are derived from dialog acts during the interaction rather than annotations. The components of belief state and goal state can be found at [Utils](https://github.com/truthless11/MADPL/blob/master/utils.py).

**Comment by gumowangfei** [comment]
Thanks! In addition, why are there 9 domains in self.domain? Dialog act is marked according to what rules? Why do some slots and values ​​are none, none?

**Comment by truthless11** [comment]
9 domains and the set of dialog acts can be found in [Config](https://github.com/truthless11/MADPL/blob/master/config.py). The scheme of dialog acts derives from the MultiWOZ corpus directly. You can refer to the paper and its data for more details.
